name: 

on:
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at midnight

jobs:
  run_script:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Use the latest version compatible

      - name: Set up Python
        uses: actions/setup-python@v4 # Use the latest version compatible
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scrapper
        run: python scrapper.py